const SUPABASE_URL='https://mijtwizvmfkhgaqzwexd.supabase.co';
const SUPABASE_KEY='sb_publishable_nR_xKWMM77WTcypkrKzxOg_8MvqKTiC';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const demoProfiles=[
 {id:'d1',name:'Amara Okafor',role:'Screenwriter',location:'Lagos, Nigeria',bio:'Stories rooted in African life, youth and human connection.',skills:['Drama','Series','Dialogue'],verified:true},
 {id:'d2',name:'Tobi Adebayo',role:'Director / Cinematographer',location:'Ibadan, Nigeria',bio:'Visual storyteller building bold, intimate films.',skills:['Direction','Cinematography','Documentary'],verified:true},
 {id:'d3',name:'Zainab Yusuf',role:'Actor',location:'Abuja, Nigeria',bio:'Actor and theatre maker exploring contemporary African stories.',skills:['Acting','Theatre','Voice'],verified:false},
 {id:'d4',name:'Daniel Mensah',role:'Producer',location:'Accra, Ghana',bio:'Independent producer connecting great stories to audiences.',skills:['Production','Development','Distribution'],verified:true}
];
const demoProjects=[
 {title:'The Last Bus',meta:'Short Film · Drama',owner:'Amara Okafor',desc:'A teenage girl gets one final chance to say goodbye before leaving home.',tag:'Seeking Producer'},
 {title:'After Rain',meta:'Documentary · 24 min',owner:'Tobi Adebayo',desc:'A visual portrait of young creatives rebuilding after a difficult season.',tag:'In Development'},
 {title:'Market Day',meta:'Feature Film · Comedy',owner:'Daniel Mensah',desc:'Three friends discover that one chaotic market day can change everything.',tag:'Seeking Screenwriter'}
];
const demoOpps=[
 {title:'Casting: Young Lead — Short Film',type:'Casting',loc:'Lagos / Hybrid',deadline:'Oct 12',comp:'Paid',desc:'Independent short film seeking a young lead actor for a character-driven story.'},
 {title:'Screenwriter Wanted — 15min Drama',type:'Writing',loc:'Remote',deadline:'Oct 18',comp:'Negotiable',desc:'Producer looking for a writer to develop a contained Nigerian drama.'},
 {title:'Cinematographer — Documentary',type:'Crew',loc:'Ibadan',deadline:'Oct 25',comp:'Paid',desc:'Small documentary team seeking a cinematographer for a 2-day shoot.'}
];
let state={tab:'Home',search:'',profiles:demoProfiles,projects:demoProjects,opps:demoOpps,user:null,modal:null,toast:''};
const icons={Home:'⌂',Discover:'⌕',Projects:'▣',Opportunities:'✦',Messages:'◌',Profile:'◉'};
function logo(){return `<div class="logo"><span class="logoMark">P</span><span>REEL<span>PAGE</span></span></div>`}
function avatar(name,cls=''){return `<div class="avatar ${cls}">${name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div>`}
function setTab(t){state.tab=t;render()}
function render(){
 document.getElementById('app').innerHTML=`<div class="shell"><aside class="side"><div class="brand">${logo()}<div class="brandLine"></div></div><nav>${Object.keys(icons).map(t=>`<button class="nav ${state.tab===t?'active':''}" onclick="setTab('${t}')"><b>${icons[t]}</b><span>${t}</span></button>`).join('')}</nav><div class="sideBottom"><button class="create" onclick="openCreate()">＋ Create</button><div class="profileMini">${avatar(state.user?.full_name||'Guest')}<div><strong>${state.user?.full_name||'Guest'}</strong><small>${state.user?.role||'Explore ReelPage'}</small></div></div></div></aside><main><header><div class="mobileBrand">${logo()}</div><div class="search"><span>⌕</span><input value="${state.search}" oninput="state.search=this.value;render()" placeholder="Search creatives, projects, opportunities..."></div><div class="headerActions"><button class="ghost" onclick="openAuth()">${state.user?'Account':'Sign in'}</button><button class="bell">◔</button></div></header><section class="content">${page()}</section></main></div>${state.modal?modal():''}${state.toast?`<div class="toast">${state.toast}</div>`:''}`;
}
function page(){switch(state.tab){case'Discover':return discover();case'Projects':return projects();case'Opportunities':return opportunities();case'Messages':return messages();case'Profile':return profile();default:return home()}}
function home(){return `<div class="eyebrow">THE CREATIVE NETWORK</div><div class="hero"><div><h1>Build your <em>creative</em> world.</h1><p>ReelPage helps filmmakers, writers, actors, producers and creative professionals discover one another, build portfolios and turn connections into real projects.</p><div class="heroBtns"><button class="primary" onclick="setTab('Discover')">Discover Creatives →</button><button class="outline" onclick="setTab('Opportunities')">Explore Opportunities</button></div></div><div class="heroArt"><div class="orbit o1"></div><div class="orbit o2"></div><div class="filmCard"><span>REEL</span><strong>PAGE</strong><small>CONNECT · CREATE · COLLABORATE</small></div></div></div><div class="sectionHead"><div><h2>Made for the people who make things</h2><p>Not a follower counter. A place to find the person your next story needs.</p></div><button class="link" onclick="setTab('Discover')">View all creatives →</button></div><div class="people">${state.profiles.slice(0,4).map(profileCard).join('')}</div><div class="grid2"><section class="panel"><div class="sectionHead compact"><div><h2>Featured projects</h2><p>Stories looking for their next collaborator.</p></div><button class="link" onclick="setTab('Projects')">See all →</button></div>${state.projects.slice(0,3).map(projectRow).join('')}</section><section class="panel"><div class="sectionHead compact"><div><h2>Open opportunities</h2><p>Real reasons to come back.</p></div><button class="link" onclick="setTab('Opportunities')">Explore →</button></div>${state.opps.slice(0,3).map(oppRow).join('')}</section></div>`}
function discover(){let q=state.search.toLowerCase();let ps=state.profiles.filter(p=>(p.name+p.role+p.location+p.skills.join(' ')).toLowerCase().includes(q));return `<div class="pageTitle"><div><div class="eyebrow">DISCOVER</div><h1>Find your people.</h1><p>Search the creative industry by role, skill or location.</p></div><button class="primary" onclick="openCreate('profile')">Create your ReelPage</button></div><div class="filterbar"><button class="chip active">All</button><button class="chip">Actors</button><button class="chip">Writers</button><button class="chip">Directors</button><button class="chip">Producers</button><button class="chip">Crew</button></div><div class="discoverGrid">${ps.map(profileCard).join('')}</div>`}
function projects(){return `<div class="pageTitle"><div><div class="eyebrow">PROJECTS</div><h1>Stories in motion.</h1><p>Discover films and creative projects looking for collaborators.</p></div><button class="primary" onclick="openCreate('project')">＋ New project</button></div><div class="projectGrid">${state.projects.map(projectCard).join('')}</div>`}
function opportunities(){return `<div class="pageTitle"><div><div class="eyebrow">OPPORTUNITIES</div><h1>Find the next door.</h1><p>Casting, writing, crew calls, fellowships and production opportunities.</p></div><button class="primary" onclick="openCreate('opportunity')">＋ Post opportunity</button></div><div class="oppList">${state.opps.map(oppCard).join('')}</div>`}
function messages(){return `<div class="pageTitle"><div><div class="eyebrow">MESSAGES</div><h1>Make the connection count.</h1><p>Project conversations belong here, not buried in comment sections.</p></div></div><div class="messages"><div class="conversationList">${demoProfiles.map((p,i)=>`<button class="conversation" onclick="showToast('Messaging is ready for your Supabase account.')">${avatar(p.name)}<div><strong>${p.name}</strong><small>${['I have a project I think you’ll like.','Loved your portfolio.','Are you available for a shoot?','Let’s talk about the script.'][i]}</small></div><time>${i+1}h</time></button>`).join('')}</div><div class="emptyChat"><div class="chatIcon">◌</div><h2>Your creative inbox.</h2><p>Select a conversation to start collaborating.</p></div></div>`}
function profile(){let u=state.user;return `<div class="profileHero"><div class="profileCover"></div><div class="profileIdentity">${avatar(u?.full_name||'Your Name','large') }<div><div class="eyebrow">YOUR REELPAGE</div><h1>${u?.full_name||'Your Creative Identity'}</h1><p>${u?.role||'Creative'} · ${u?.location||'Nigeria'}</p></div><button class="primary" onclick="openAuth()">${u?'Edit profile':'Create profile'}</button></div></div><div class="profileBody"><section class="panel"><h2>About</h2><p>${u?.bio||'Your ReelPage is where your work, credits, skills and creative identity live. Sign in to make this page yours.'}</p></section><section class="panel"><h2>Portfolio</h2><div class="portfolioPlaceholder"><span>＋</span><strong>Add your first work</strong><small>Projects, films, writing, photography, design and more.</small></div></section></div>`}
function profileCard(p){return `<article class="person" onclick="openProfile('${p.id}')">${avatar(p.name,'xl')}<div class="verified">${p.verified?'✓':''}</div><h3>${p.name}</h3><p>${p.role}</p><small>${p.location}</small><div class="tags">${p.skills.slice(0,2).map(s=>`<span>${s}</span>`).join('')}</div><button class="connect" onclick="event.stopPropagation();connect('${p.id}')">Connect</button></article>`}
function projectCard(p){return `<article class="project"><div class="poster"><span>REELPAGE</span><strong>${p.title.split(' ').slice(0,2).join(' ')}</strong></div><div class="projectInfo"><span class="tiny">${p.meta}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="projectFoot"><span>${p.tag}</span><button class="link" onclick="showToast('Project details opened.')">View →</button></div></div></article>`}
function projectRow(p){return `<div class="row"><div class="miniPoster"></div><div><strong>${p.title}</strong><small>${p.meta} · ${p.tag}</small></div><button class="arrow" onclick="showToast('Project details opened.')">→</button></div>`}
function oppCard(o){return `<article class="opp"><div class="oppIcon">✦</div><div class="oppMain"><div class="tiny">${o.type} · ${o.loc}</div><h3>${o.title}</h3><p>${o.desc}</p><div class="oppMeta"><span>Deadline ${o.deadline}</span><span>${o.comp}</span></div></div><button class="outline small" onclick="applyOpp('${o.title.replaceAll("'","")}')">View / Apply</button></article>`}
function oppRow(o){return `<div class="row"><div class="oppDot">✦</div><div><strong>${o.title}</strong><small>${o.type} · ${o.loc} · ${o.comp}</small></div><button class="arrow" onclick="applyOpp('${o.title.replaceAll("'","")}')">→</button></div>`}
function modal(){return `<div class="backdrop" onclick="closeModal(event)"><div class="modal" onclick="event.stopPropagation()">${state.modal.type==='auth'?authModal():state.modal.type==='person'?personModal():createModal(state.modal.type)}</div></div>`}
function authModal(){return `<button class="close" onclick="state.modal=null;render()">×</button><div class="modalLogo">${logo()}</div><div class="eyebrow">JOIN THE NETWORK</div><h2>Claim your ReelPage.</h2><p>Use your email to sign in or create an account. No password needed.</p><input id="authEmail" class="input" type="email" placeholder="you@example.com"><button class="primary full" onclick="magicLink()">Send magic link →</button><small class="modalNote">We’ll send a secure sign-in link to your inbox.</small>`}
function personModal(){let p=state.modal.p;return `<button class="close" onclick="state.modal=null;render()">×</button><div class="personTop">${avatar(p.name,'large')}<div><div class="eyebrow">${p.role.toUpperCase()}</div><h2>${p.name}</h2><p>${p.location}</p></div></div><p class="bio">${p.bio}</p><div class="tags big">${p.skills.map(s=>`<span>${s}</span>`).join('')}</div><button class="primary full" onclick="connect('${p.id}')">Connect with ${p.name.split(' ')[0]}</button>`}
function createModal(type){let title=type==='project'?'Create a project':type==='opportunity'?'Post an opportunity':'Create your ReelPage';return `<button class="close" onclick="state.modal=null;render()">×</button><div class="eyebrow">REELPAGE</div><h2>${title}</h2><p>Build the thing that brings your next creative connection closer.</p><input id="createTitle" class="input" placeholder="${type==='project'?'Project title':type==='opportunity'?'Opportunity title':'Your full name'}"><textarea id="createDesc" class="input area" placeholder="${type==='profile'?'Tell people what you make...':'Describe the opportunity or project...'}"></textarea><button class="primary full" onclick="createItem('${type}')">Create →</button><small class="modalNote">${state.user?'Saved to your ReelPage account.':'Sign in first to save this to your account.'}</small>`}
function openAuth(){state.modal={type:'auth'};render()}
function openProfile(id){let p=state.profiles.find(x=>x.id===id);state.modal={type:'person',p};render()}
function openCreate(type='profile'){if(!state.user){openAuth();return}state.modal={type};render()}
function closeModal(e){if(e.target.classList.contains('backdrop')){state.modal=null;render()}}
async function magicLink(){let email=document.getElementById('authEmail').value.trim();if(!email)return showToast('Enter your email first.');const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href,data:{full_name:'ReelPage Member'}}});if(error)showToast(error.message);else{state.modal=null;showToast('Check your email for your ReelPage sign-in link.');}}
async function loadUser(){const {data}=await sb.auth.getUser();state.user=data.user?.user_metadata?{...data.user.user_metadata,email:data.user.email,id:data.user.id}:null;if(data.user){const {data:p}=await sb.from('profiles').select('*').eq('id',data.user.id).maybeSingle();if(p)state.user={...p,email:data.user.email}}}
async function connect(id){if(!state.user){openAuth();return}if(id.startsWith('d')){state.modal=null;showToast('Connection request ready — demo profile.');return}const {error}=await sb.from('connections').upsert({requester_id:state.user.id,addressee_id:id,status:'pending'});state.modal=null;showToast(error?'Could not send connection request.':'Connection request sent.');}
function applyOpp(t){if(!state.user){openAuth();return}showToast('Application flow opened for '+t+'.')}
async function createItem(type){let title=document.getElementById('createTitle').value.trim(),desc=document.getElementById('createDesc').value.trim();if(!title)return showToast('Give it a title first.');if(!state.user)return openAuth();let error=null;if(type==='project'){({error}=await sb.from('projects').insert({owner_id:state.user.id,title,description:desc,format:'Short Film',genre:'Drama'}))}else if(type==='opportunity'){({error}=await sb.from('opportunities').insert({creator_id:state.user.id,title,description:desc,opportunity_type:'Other',status:'Open'}))}else{({error}=await sb.from('profiles').update({full_name:title,bio:desc}).eq('id',state.user.id));state.user.full_name=title;state.user.bio=desc}state.modal=null;showToast(error?error.message:'Created successfully.');await hydrate();}
async function hydrate(){try{let {data:p}=await sb.from('profiles').select('*').limit(24);if(p?.length)state.profiles=p.map(x=>({...x,name:x.full_name,verified:x.is_verified}));let {data:pr}=await sb.from('projects').select('*').order('created_at',{ascending:false}).limit(12);if(pr?.length)state.projects=pr.map(x=>({title:x.title,meta:[x.format,x.genre].filter(Boolean).join(' · ')||'Creative Project',owner:'ReelPage',desc:x.description||x.logline||'',tag:x.status||'In Development'}));let {data:o}=await sb.from('opportunities').select('*').order('created_at',{ascending:false}).limit(12);if(o?.length)state.opps=o.map(x=>({title:x.title,type:x.opportunity_type,loc:x.location||'Remote',deadline:x.deadline?new Date(x.deadline).toLocaleDateString(): 'Open',comp:x.compensation||'See details',desc:x.description||''}));}catch(e){}render()}
function showToast(t){state.toast=t;render();setTimeout(()=>{state.toast='';render()},2800)}
sb.auth.onAuthStateChange(async()=>{await loadUser();render()});loadUser().then(hydrate);render();